export const S = {
  app: {
    "--bg": "#0D0D0D", "--surface": "#1A1A1A", "--surface2": "#242424",
    "--border": "#2A2A2A", "--text": "#F0EDE6", "--muted": "#8A8680",
    "--accent": "#D4853E", "--accentDim": "rgba(212,133,62,0.15)",
    "--success": "#5B8C5A", "--danger": "#C45B4A",
    "--font": "'DM Sans',-apple-system,system-ui,sans-serif",
    "--font-mono": "'JetBrains Mono','SF Mono',monospace",
    fontFamily: "var(--font)", background: "var(--bg)", color: "var(--text)",
    minHeight: "100vh", maxWidth: 480, margin: "0 auto", paddingBottom: 80,
    WebkitFontSmoothing: "antialiased",
  },
  tabBar: {
    position: "fixed", bottom: 0, left: 0, right: 0, display: "flex",
    justifyContent: "center", background: "rgba(13,13,13,0.95)",
    backdropFilter: "blur(20px)", borderTop: "1px solid var(--border)",
    zIndex: 100, padding: "6px 0 env(safe-area-inset-bottom,8px)",
  },
  tab: {
    flex: 1, maxWidth: 160, display: "flex", flexDirection: "column",
    alignItems: "center", gap: 2, padding: "8px 0", background: "none",
    border: "none", color: "var(--muted)", cursor: "pointer", fontFamily: "var(--font)",
  },
  tabAct: { color: "var(--accent)" },
  page: { padding: "16px 16px 24px" },
  hdr: { display: "flex", alignItems: "center", gap: 8, marginBottom: 14 },
  title: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em", margin: 0, flex: 1 },
  iconBtn: {
    background: "none", border: "none", color: "var(--text)", cursor: "pointer",
    padding: 8, borderRadius: 10, display: "flex",
  },
  pri: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
    width: "100%", padding: "13px 20px", background: "var(--accent)", color: "#fff",
    border: "none", borderRadius: 12, fontSize: 15, fontWeight: 600, cursor: "pointer",
    fontFamily: "var(--font)", marginTop: 8,
  },
  sec: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
    width: "100%", padding: "13px 20px", background: "var(--surface2)",
    color: "var(--text)", border: "1px solid var(--border)", borderRadius: 12,
    fontSize: 15, fontWeight: 500, cursor: "pointer", fontFamily: "var(--font)", marginTop: 8,
  },
  saveBtn: {
    display: "flex", alignItems: "center", gap: 5, padding: "7px 13px",
    background: "var(--accent)", color: "#fff", border: "none", borderRadius: 10,
    fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "var(--font)",
  },
  danger: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
    width: "100%", padding: 11, background: "none", color: "var(--danger)",
    border: "1px solid var(--danger)", borderRadius: 12, fontSize: 13,
    fontWeight: 500, cursor: "pointer", fontFamily: "var(--font)", marginTop: 24,
  },
  addBtn: {
    display: "flex", alignItems: "center", gap: 6, padding: "10px 14px",
    background: "var(--accentDim)", color: "var(--accent)",
    border: "1px dashed rgba(212,133,62,0.4)", borderRadius: 10, fontSize: 13,
    fontWeight: 500, cursor: "pointer", fontFamily: "var(--font)", marginTop: 6, width: "100%",
  },
  addSm: {
    display: "inline-flex", alignItems: "center", gap: 3, padding: "4px 9px",
    background: "var(--accentDim)", color: "var(--accent)",
    border: "1px dashed rgba(212,133,62,0.4)", borderRadius: 7, fontSize: 11,
    fontWeight: 500, cursor: "pointer", fontFamily: "var(--font)", marginTop: 4,
  },
  mini: { background: "none", border: "none", color: "var(--muted)", cursor: "pointer", padding: 3, display: "flex" },
  empty: { display: "flex", flexDirection: "column", alignItems: "center", padding: "60px 20px", textAlign: "center" },
  mutedTxt: { color: "var(--muted)", fontSize: 14, marginBottom: 14 },
  rCard: {
    display: "block", width: "100%", textAlign: "left", background: "var(--surface)",
    border: "1px solid var(--border)", borderRadius: 14, padding: 14,
    cursor: "pointer", fontFamily: "var(--font)", color: "var(--text)",
  },
  badge: { padding: "3px 10px", borderRadius: 20, fontSize: 10, fontWeight: 600, color: "#fff", background: "var(--accent)" },
  secTabs: { display: "flex", gap: 3, marginBottom: 14, background: "var(--surface)", borderRadius: 10, padding: 3 },
  secTab: {
    flex: 1, padding: "9px 6px", background: "none", border: "none",
    color: "var(--muted)", fontSize: 13, fontWeight: 500, borderRadius: 8,
    cursor: "pointer", fontFamily: "var(--font)",
  },
  secTabAct: { background: "var(--surface2)", color: "var(--text)" },
  col: { display: "flex", flexDirection: "column", gap: 8 },
  row: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 4 },
  lbl: { fontSize: 13, color: "var(--muted)", fontWeight: 500 },
  titleIn: {
    width: "100%", padding: "10px 0", background: "none", border: "none",
    borderBottom: "2px solid var(--border)", color: "var(--text)", fontSize: 22,
    fontWeight: 700, fontFamily: "var(--font)", outline: "none",
  },
  sel: {
    padding: "9px 10px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 8, color: "var(--text)", fontSize: 14, fontFamily: "var(--font)", minWidth: 100,
  },
  numIn: {
    padding: "9px 10px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 8, color: "var(--text)", fontSize: 14, fontFamily: "var(--font-mono)",
    width: 80, textAlign: "right",
  },
  numSm: {
    padding: "4px 6px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 6, color: "var(--text)", fontSize: 13, fontFamily: "var(--font-mono)", textAlign: "right",
  },
  dateIn: {
    padding: "9px 10px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 8, color: "var(--text)", fontSize: 14, fontFamily: "var(--font)",
    colorScheme: "dark", flex: 1,
  },
  timeIn: {
    padding: "9px 10px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 8, color: "var(--text)", fontSize: 14, fontFamily: "var(--font-mono)",
    colorScheme: "dark", width: 90,
  },
  inIn: {
    display: "block", width: "100%", padding: "5px 7px", background: "var(--surface2)",
    border: "1px solid var(--border)", borderRadius: 6, color: "var(--text)", fontSize: 13,
    fontFamily: "var(--font)", outline: "none", boxSizing: "border-box",
  },
  inSel: {
    padding: "3px 5px", background: "var(--surface2)", border: "1px solid var(--border)",
    borderRadius: 6, color: "var(--text)", fontSize: 11, fontFamily: "var(--font)",
  },
  ta: {
    width: "100%", padding: 10, background: "var(--surface2)", border: "1px solid var(--border)",
    borderRadius: 10, color: "var(--text)", fontSize: 14, fontFamily: "var(--font)",
    resize: "vertical", outline: "none", boxSizing: "border-box",
  },
  taSm: {
    width: "100%", padding: 6, background: "var(--surface2)", border: "1px solid var(--border)",
    borderRadius: 6, color: "var(--text)", fontSize: 12, fontFamily: "var(--font)",
    resize: "vertical", outline: "none", boxSizing: "border-box",
  },
  card: { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 14, padding: 14 },
  cardT: { display: "flex", alignItems: "center", gap: 6, fontSize: 15, fontWeight: 600, margin: "0 0 6px" },
  stat: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", padding: "12px 8px", background: "var(--surface2)", borderRadius: 10, gap: 2 },
  statV: { fontSize: 16, fontWeight: 700 },
  statL: { fontSize: 10, color: "var(--muted)", textAlign: "center" },
  scBtn: {
    padding: "4px 11px", background: "var(--surface)", border: "1px solid var(--border)",
    borderRadius: 7, color: "var(--muted)", fontSize: 12, fontWeight: 600,
    cursor: "pointer", fontFamily: "var(--font-mono)",
  },
  scBtnAct: { background: "var(--accentDim)", borderColor: "var(--accent)", color: "var(--accent)" },
  stepCard: { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 11, marginBottom: 3 },
  stepN: {
    width: 20, height: 20, borderRadius: "50%", background: "var(--surface2)",
    display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10,
    fontWeight: 700, fontFamily: "var(--font-mono)", color: "var(--muted)", flexShrink: 0,
  },
};
